### ISSUE TITLE
replace the libwebrtc static lib with the dynamic library from the native build process

### ISSUE THREAD

**Issue by hthetiot** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#3]
>> Would it be better to replace the libwebrtc static lib with the dynamic library from the native build process at https://webrtc.org/native-code/ios/ ?

> Probably, but this issue is about looking for maintainers.

**Comment by hthetiot** [comment]
cc cc @ibc @saghul

**Comment by saghul** [comment]
This is actually needed, as the current version is ancient. I'd suggest to use the GoogleWebRTC CocoaPod.
