### ISSUE TITLE
PluginMediaStreamRenderer.swift Swift 4 'bringSubview' Error

### ISSUE THREAD

**Issue by banditdevelopment** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#4]
I switched to this plugin so my project had compatibility with Xcode 10. However, when I ran the build I got an error with `PluginMediaStreamRenderer.swift`, which is a file contained in the plugins folder of simplyrtc. 

I did a little research online to see if this issue was run into before, but I didn't find an easy fix. Instead, I just edited line 193 myself like so:

`// self.webView.superview?.bringSubviewToFront(self.elementView)
self.webView.superview?.bringSubview(toFront:self.elementView)`

After that, everything built correctly. 

Sorry if this is the wrong place to describe this issue I had with the plugin. Just posting here so others with the issue can fix if needed.

**Comment by nanasheng** [comment]
Did you use this plug-in to run successfully on ios?

**Comment by banditdevelopment** [comment]
Yes, I used it successfully for video calling (with ApiRTC) between an iPhone X (iOS 12) and a iPad Pro 2017 (iOS 13 beta).

**Comment by nanasheng** [comment]
> Yes, I used it successfully for video calling (with ApiRTC) between an iPhone X (iOS 12) and a iPad Pro 2017 (iOS 13 beta).



> Yes, I used it successfully for video calling (with ApiRTC) between an iPhone X (iOS 12) and a iPad Pro 2017 (iOS 13 beta).

Can you give me a demo, I failed.

**Comment by banditdevelopment** [comment]
What exactly is going wrong? Can you please provide a description of the error?

**Comment by nanasheng** [comment]
My js code is for reference to this website: https://www.scaledrone.com/blog/webrtc-tutorial-simple-video-chat.The result of the run is
![image](https://user-images.githubusercontent.com/21351393/60406186-3fb3a800-9be7-11e9-957f-ee5a62b794c0.png)
But the page didn't respond.I don't know how to modify the js code to make it work.

**Comment by nanasheng** [comment]
I have run successfully. Thank you very much.

**Comment by hthetiot** [comment]
@nanasheng @banditdevelopment 
This fork as been merged into official repository that I maintain now, testing welcome.

> cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc.git#master --verbose

https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/364

**Comment by hthetiot** [comment]
@banditdevelopment can you check issue on https://github.com/cordova-rtc/cordova-plugin-iosrtc/issue for following change for iOS 13.

> // self.webView.superview?.bringSubviewToFront(self.elementView)
> self.webView.superview?.bringSubview(toFront:self.elementView)
