### ISSUE TITLE
stream remote video real time

### ISSUE THREAD

**Issue by AmrAbdalrahman** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#5]
First, thanks for your efforts in maintenance [cordova-plugin-iosrtc ](https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc) I tried using this update of the plugin when making a video calls using[ apirtc plugin](https://github.com/apizee/ApiRTC-ionic) get the error in the attached screenshot. 
I'm using Xcode 10.2 with Swift version 4.2.

![Screen Shot 2019-07-14 at 10 43 51 AM](https://user-images.githubusercontent.com/19286599/61181677-cd50b800-a629-11e9-96ee-813775c21f3f.png)

**Comment by hthetiot** [comment]
@AmrAlmagic  This plugin work perfectly, with proper WebRTC usage. (blob://blobinternal should not be there)
I dot not support for-profit WebRTC API library integration, you can pay them if you need it to work.
- https://www.apizee.com/solutions-pricing/
- https://github.com/apizee/ApiRTC-ios
- https://github.com/apizee/ApiRTC-ionic/blob/master/package.json#L38 (need update anyway)

**Comment by hthetiot** [comment]
cc @ibc @saghul

**Comment by ibc** [comment]
Please do not mention me in all issues. I'm not maintaining this project.

**Comment by AmrAbdalrahman** [comment]
@hthetiot  I already use [apizee](https://www.apizee.com/solutions-pricing/) and works now well thanks for your helping!
