### ISSUE TITLE
Outgoing call Error

### ISSUE THREAD

**Issue by Sfinx** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#6]
When making outgoing call with SIP.js (0.14.6) :

```
sip.inviteclientcontext | peerConnection-SetLocalDescriptionFailed
message: "setLocalDescription() must be called with a RTCSessionDescription instance as first argument"
```

What can be the problem ?

**Comment by Sfinx** [comment]
Ok, found, change the SessionDescriptionHandler.prototype.createOfferOrAnswer to

```
return pc.setLocalDescription(!!window.cordova ? new RTCSessionDescription(sdp) : sdp);
```

**Comment by hthetiot** [comment]
that nothing to do with this plugin stop using `SIP.js` and use JSSip and learn WebRTC 1.0 API.

**Comment by Sfinx** [comment]
I've stopped use this plugin along with cordova. jssip is undocumented messy shit btw ;)

**Comment by hthetiot** [comment]
@Sfinx jssip and Cordova is well documented the problem is developper like you not the libraries.

**Comment by Sfinx** [comment]
I'm totally happy with SIP.js. jssip is for developers like you
