### ISSUE TITLE
video in wkwebview and device rotation problem

### ISSUE THREAD

**Issue by Sfinx** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#7]
Anybody having the same problems as I when video is misaligned after device rotation in wkwebview ?  The uiwebview is ok, but it is outdated and slow. How to fix this ?

**Comment by hthetiot** [comment]
Depend if i become maintainer of the original repository located here in short term https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc then I would merge a fix for that.

**Comment by hthetiot** [comment]
Note: I'm also aware of an issue with video position using iOS device with and without notch.

**Comment by hthetiot** [comment]
cc @ibc @saghul

**Comment by Sfinx** [comment]
I see. Seems like Cordova is dying (for capacitor/proton) so this issue is not relevant at global

**Comment by hthetiot** [comment]
@Sfinx if dying why are you using it.
This is stupid comment.
