### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by cpgb85** [simplyrtc/cordova-plugin-iosrtc-simplyrtc#8]
I am having an issue building the project. As the title states, that is the error. I don't have any more information than that. Some people have said add a user defined build setting labeled "SWIFT_ENABLE_BATCH_MODE" and set it to "NO" but that didn't help.

**Comment by hthetiot** [comment]
Thank you @cpgb85 can you report the issue here:
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues

I'm now the maintainer of the official plugin and I'm working on releasing v5.0.0:
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/364

**Comment by hthetiot** [comment]
Was Probably due missing xcode on packake.json.
